//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_SP_UsingMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CTSDBEntities : DbContext
    {
        public CTSDBEntities()
            : base("name=CTSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetEmpInfo_Result> GetEmpInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmpInfo_Result>("GetEmpInfo");
        }
    }
}
